services:
  windows:
    image: dockur/windows
    container_name: windows
    ports:
      - 3389:3389
    environment:
      # This downloads Windows 11 automatically
      VERSION: "11"
      # Using your massive resources
      RAM_SIZE: "64G" 
      CPU_CORES: "24"
      DISK_SIZE: "500G"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    restart: on-failure
